<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4qos6km\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4qos6km/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4qos6km.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4qos6km\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4qos6km\appProdProjectContainer([
    'container.build_hash' => '4qos6km',
    'container.build_id' => '64aa75d6',
    'container.build_time' => 1629905364,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4qos6km');
